var enStrings = {
	"hello_world": "Hello there.",
	"enter_username": "Enter your username.",
	"enter_username_non_empty": "Enter your username (it can't be empty).",
	"enter_room_name": "Enter the room name to join or create one.",
	"shareable_link": "Your sharable link to invite people to this room:",
	"joined_game": "has joined the game!",
	"left_game": "has left the game",
	"you": "you",
	"sends_message": "Sends a message",
	"column_full": "This column is already full!",
	"new_game": "New game",
	"confirm_new_game": "This will create a new game and reset all current progress. Are you sure?",
	"": "",
}